application: adamspdapp
version: 4
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /static
  static_dir: static

- url: /scripts
  static_dir: scripts

- url: /includes
  static_dir: includes

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
